services:
  - type: web
    name: vintage-bot
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    rootDir: .                     # ← заставляет искать файлы в корне
    autoDeploy: true

    envVars:
      - key: BOT_TOKEN
        sync: false
