services:
  - type: web  # Web-сервис для webhook
    name: vintage-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    rootDir: .
    autoDeploy: true
